### ISSUE TITLE
set -o errexit causes problems if -- option separator missing

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#21]
easy fix, just need an `||true`

**Comment by gdevenyi** [comment]
Resolved? I don't have issues with this.

**Comment by zbeekman** [comment]
Sorry, no, not resolved yet: https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L195

This should cause problems, but it's possible that theres an error in the test conditional that's causing it to evaluate to true in certain instances... It's a super simple fix though...

**Comment by zbeekman** [comment]
Really the best solution is probably a one line `if`... Although, perhaps errexit is off in that portion of the code right now... either way it would be good practice.
